In [71]:
import pandas as pd
import numpy as np

<h2> Combine all Oscars data into one file <h2>

In [72]:
#Dictionary with categories: 

dict = {

'ACTOR': 'ACTOR IN A LEADING ROLE',
'ACTOR IN A LEADING ROLE':'ACTOR IN A LEADING ROLE',
'LEAD ACTOR':'ACTOR IN A LEADING ROLE',


'ACTRESS':   'ACTRESS IN A LEADING ROLE',
'ACTRESS IN A LEADING ROLE':   'ACTRESS IN A LEADING ROLE',
'LEAD ACTRESS':'ACTRESS IN A LEADING ROLE',


'ACTOR IN A SUPPORTING ROLE': 'ACTOR IN A SUPPORTING ROLE',
'SUPPORTING ACTOR':'ACTOR IN A SUPPORTING ROLE',

'ACTRESS IN A SUPPORTING ROLE':   'ACTRESS IN A SUPPORTING ROLE',
'SUPPORTING ACTRESS':'ACTRESS IN A SUPPORTING ROLE',

'CINEMATOGRAPHY':  'CINEMATOGRAPHY',
'CINEMATOGRAPHY (Black-and-White)':  'CINEMATOGRAPHY',
'CINEMATOGRAPHY (Color)':  'CINEMATOGRAPHY',

'DIRECTING (Comedy Picture)':  'DIRECTING',
'DIRECTING (Dramatic Picture)':  'DIRECTING',
'DIRECTING': 'DIRECTING',
    'DIRECTOR':'DIRECTING',

'OUTSTANDING PICTURE': 'BEST PICTURE',
'OUTSTANDING MOTION PICTURE': 'BEST PICTURE',
'BEST MOTION PICTURE': 'BEST PICTURE',
'BEST PICTURE':'BEST PICTURE',

}

In [73]:
#1929-2016

till2016 = pd.read_csv('data/database_oscars_goodone.csv')  

#Fix year 

yrs = {
    '1927/1928':'1928',
    '1928/1929':'1929',
    '1929/1930':'1930',
    '1930/1931':'1931',
    '1931/1932':'1932',
    '1932/1933':'1933',    
}

till2016=till2016.replace({'Year':yrs})
till2016['Year']=pd.to_numeric(till2016['Year'])+1

In [74]:
till2016['Award']=till2016['Award'].str.upper()
till2016['Award']=till2016['Award'].map(dict)
till2016=till2016[till2016['Award'].notnull()]
till2016=till2016.copy()

In [75]:
till2016.drop(columns=['Ceremony'], inplace=True)

In [76]:
till2016=till2016[till2016['Year']>1940]

In [77]:
#2017
osc17 = pd.read_csv('data/past_nominations.csv') #2000-2017
osc17=osc17[osc17['Year']==2017]
osc17=osc17[osc17['Award'].isin(dict)]

In [78]:
#2019 nominations
osc19 = pd.read_csv('data/2019_nominations.csv')
osc19=osc19[osc19['Award'].isin(dict)].reset_index().drop(columns=['index', 'Detail'])

In [79]:
#Add 2019 winners 
osc19['winner']=np.nan
osc19.iloc[3,4]=1
osc19.iloc[5,4]=1
osc19.iloc[12,4]=1
osc19.iloc[17,4]=1
osc19.iloc[23,4]=1
osc19.iloc[28,4]=1
osc19.iloc[34,4]=1

In [80]:
#Import 2020 oscars, will process them separately
osc2020=pd.read_csv('data/2020nominees.csv')
osc2020=osc2020.drop(columns=osc2020.columns[0])
osc2020['category']=osc2020['category'].str.upper()
osc2020=osc2020[osc2020['category'].isin(dict)]

In [81]:
osc2020
name=osc2020[osc2020['name'].isnull()]
name['name']=name['movie']

osc2020=pd.concat([osc2020[9:],name], axis=0)
osc2020=osc2020.copy()
osc2020['name']=osc2020['name'].str.title()
osc2020['movie']=osc2020['movie'].str.title()

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [82]:
osc2020

,category,name,movie
9,LEAD ACTOR,Antonio Banderas,Pain And Glory
10,LEAD ACTOR,Leonardo Dicaprio,Once Upon A Time... In Hollywood
11,LEAD ACTOR,Adam Driver,Marriage Story
12,LEAD ACTOR,Joaquin Phoenix,Joker
13,LEAD ACTOR,Jonathan Pryce,The Two Popes
14,LEAD ACTRESS,Cynthia Erivo,Harriet
15,LEAD ACTRESS,Scarlett Johansson,Marriage Story
16,LEAD ACTRESS,Saoirse Ronan,Little Women
17,LEAD ACTRESS,Charlize Theron,Bombshell
18,LEAD ACTRESS,Renee Zellweger,Judy
19,SUPPORTING ACTOR,Tom Hanks,A Beautiful Day In The Neighborhood
20,SUPPORTING ACTOR,Anthony Hopkins,The Two Popes
21,SUPPORTING ACTOR,Al Pacino,The Irishman
22,SUPPORTING ACTOR,Joe Pesci,The Irishman
23,SUPPORTING ACTOR,Brad Pitt,Once Upon A Time... In Hollywood
24,SUPPORTING ACTRESS,Kathy Bates,Richard Jewell
25,SUPPORTING ACTRESS,Laura Dern,Marriage Story
26,SUPPORTING ACTRESS,Scarlett Johannson,Jojo Rabbit
27,SUPPORTING ACTRESS,Florence Pugh,Little Women
28,SUPPORTING ACTRESS,Margot Robbie,Bombshell
29,DIRECTOR,Martin Scorsese,The Irishman
30,DIRECTOR,Todd Phillips,Joker
31,DIRECTOR,Sam Mendes,1917
32,DIRECTOR,Quentin Tarantino,Once Upon A Time... In Hollywood
33,DIRECTOR,Bong Joon Ho,Parasite
34,CINEMATOGRAPHY,Rodrigo Prieto,The Irishman
35,CINEMATOGRAPHY,Lawrence Sher,Joker
36,CINEMATOGRAPHY,Jarin Blaschke,The Lighthouse
37,CINEMATOGRAPHY,Roger Deakins,1917
38,CINEMATOGRAPHY,Robert Richardson,Once Upon A Time... In Hollywood
0,BEST PICTURE,Ford V Ferrari,Ford V Ferrari
1,BEST PICTURE,The Irishman,The Irishman
2,BEST PICTURE,Jojo Rabbit,Jojo Rabbit
3,BEST PICTURE,Joker,Joker
4,BEST PICTURE,Little Women,Little Women
5,BEST PICTURE,Marriage Story,Marriage Story
6,BEST PICTURE,1917,1917
7,BEST PICTURE,Once Upon A Time... In Hollywood,Once Upon A Time... In Hollywood
8,BEST PICTURE,Parasite,Parasite

In [83]:
till2016

,Year,Award,Winner,Name,Film
928,1941,ACTOR IN A LEADING ROLE,NaN,Charles Chaplin,The Great Dictator
929,1941,ACTOR IN A LEADING ROLE,NaN,Henry Fonda,The Grapes of Wrath
930,1941,ACTOR IN A LEADING ROLE,NaN,Raymond Massey,Abe Lincoln in Illinois
931,1941,ACTOR IN A LEADING ROLE,NaN,Laurence Olivier,Rebecca
932,1941,ACTOR IN A LEADING ROLE,1.0,James Stewart,The Philadelphia Story
...,...,...,...,...,...
9916,2016,BEST PICTURE,NaN,Mad Max: Fury Road,"Doug Mitchell and George Miller, Producers"
9917,2016,BEST PICTURE,NaN,The Martian,"Simon Kinberg, Ridley Scott, Michael Schaefer ..."
9918,2016,BEST PICTURE,NaN,The Revenant,"Arnon Milchan, Steve Golin, Alejandro G. Iñárr..."
9919,2016,BEST PICTURE,NaN,Room,"Ed Guiney, Producer"
9920,2016,BEST PICTURE,1.0,Spotlight,"Michael Sugar, Steve Golin, Nicole Rocklin and..."

In [84]:
#combine till2016, 2017, 2019

till2016.columns=['Year','Award','Winner','Nominee','Movie']
till2016=till2016[['Year', 'Award', 'Movie', 'Nominee', 'Winner']]
osc19.columns=osc19.columns.str.title()

print(till2016.columns)
print(osc17.columns)
print(osc19.columns)

Index(['Year', 'Award', 'Movie', 'Nominee', 'Winner'], dtype='object')
Index(['Year', 'Award', 'Movie', 'Nominee', 'Winner'], dtype='object')
Index(['Year', 'Award', 'Movie', 'Nominee', 'Winner'], dtype='object')

In [85]:
osc=pd.concat([till2016,osc17,osc19],axis=0, sort=False)
osc['Movie']=osc['Movie'].str.title().str.strip()
osc['Nominee']=osc['Nominee'].str.title().str.strip()

#let's separate best picture nominations from here: 

picture=osc[osc['Award']=='BEST PICTURE']
picture=picture.copy()

print(picture.shape)
#We still need to add 2018, once we match the nominations

(435, 5)

In [86]:
osc

,Year,Award,Movie,Nominee,Winner
928,1941,ACTOR IN A LEADING ROLE,The Great Dictator,Charles Chaplin,NaN
929,1941,ACTOR IN A LEADING ROLE,The Grapes Of Wrath,Henry Fonda,NaN
930,1941,ACTOR IN A LEADING ROLE,Abe Lincoln In Illinois,Raymond Massey,NaN
931,1941,ACTOR IN A LEADING ROLE,Rebecca,Laurence Olivier,NaN
932,1941,ACTOR IN A LEADING ROLE,The Philadelphia Story,James Stewart,1.0
...,...,...,...,...,...
33,2019,BEST PICTURE,The Favourite,The Favourite,NaN
34,2019,BEST PICTURE,Green Book,Green Book,1.0
35,2019,BEST PICTURE,Roma,Roma,NaN
36,2019,BEST PICTURE,A Star Is Born,A Star Is Born,NaN
37,2019,BEST PICTURE,Vice,Vice,NaN

<h2>Feature engineering: Add nominations</h2>

In [87]:
#Function to add film nomination in other categories 

def match_awards(all_oscars, picture):
    
    picture=picture.copy()

    #Remove "BEST PICTURE" from the list
    awards=all_oscars['Award'].unique()
    n=np.where(awards=="BEST PICTURE")
    awards=np.delete(awards,n[0][0])

    for award in awards: 
        subset=pd.concat([all_oscars[all_oscars['Award']==award]['Movie'],all_oscars[all_oscars['Award']==award]['Nominee']])
        name=award.replace(' ','_')+"_nomination"
        picture[name]=picture['Nominee'].isin(subset)
    return picture

In [88]:
picture=match_awards(osc, picture)

In [89]:
#Add 2018 
osc18=pd.read_csv('data/missing_data.csv') #Combine with data when matched other awards 
osc18=osc18[osc18['year']==2018]
osc18=osc18[['year', 'award', 'movie', 'nominee', 'winner','lead_actor_nomination', 
       'lead_actor_nomination', 
       'cinematography_nomination', 'directing_nomination',
       'support_actor_nomination', 'support_actress_nomination']]
osc18.columns=picture.columns
picture=pd.concat([picture, osc18], axis=0)

In [90]:
picture

,Year,Award,Movie,Nominee,Winner,ACTOR_IN_A_LEADING_ROLE_nomination,ACTOR_IN_A_SUPPORTING_ROLE_nomination,ACTRESS_IN_A_LEADING_ROLE_nomination,ACTRESS_IN_A_SUPPORTING_ROLE_nomination,DIRECTING_nomination,CINEMATOGRAPHY_nomination
1199,1942,BEST PICTURE,Metro-Goldwyn-Mayer,Blossoms In The Dust,NaN,0,0,1,0,0,0
1200,1942,BEST PICTURE,Mercury,Citizen Kane,NaN,1,0,0,0,1,0
1201,1942,BEST PICTURE,Columbia,Here Comes Mr. Jordan,NaN,1,1,0,0,1,0
1202,1942,BEST PICTURE,Paramount,Hold Back The Dawn,NaN,0,0,1,0,0,0
1203,1942,BEST PICTURE,20Th Century-Fox,How Green Was My Valley,1.0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...
9,2018,BEST PICTURE,NaN,"Three Billboards Outside Ebbing, Missouri",0.0,0,0,0,0,1,0
10,2018,BEST PICTURE,NaN,The Post,0.0,0,0,0,0,0,0
11,2018,BEST PICTURE,NaN,Lady Bird,0.0,0,0,0,1,0,1
12,2018,BEST PICTURE,NaN,Dunkirk,0.0,0,0,1,1,0,0
13,2018,BEST PICTURE,NaN,Call me by your name,0.0,1,1,0,0,0,0

<h2>Add IMDB data </h2>

In [91]:
#Edit picture fields 
picture['Nominee']=picture['Nominee'].str.strip().str.title()
picture['Year']=pd.to_numeric(picture['Year'])
picture['Year_film']=picture['Year']-1
picture ['Year_film2']=picture['Year']-2
picture ['Year_film3']=picture['Year']-3

names_ = {'Cries And Whispers': 'Cries & Whispers',
         'The Godfather Part Ii':'The Godfather: Part Ii',
         'The Godfather, Part Iii':'The Godfather: Part Iii',
         "Precious: Based On The Novel 'Push' By Sapphire":'Precious',
         'The Postman (Il Postino)': 'Il Postino',
         'Henry V': 'The Chronicle History Of King Henry The Fifth With His Battell Fought At Agincourt In France'
        }

picture=picture.replace({'Nominee':names_})

In [92]:
#First, add title and genre -- this is a big DB
imdb = pd.read_csv('data/imdb/data.tsv', sep='\t', na_values='\\N')
imdb=imdb[imdb['titleType']=='movie']
imdb['primaryTitle']=imdb['primaryTitle'].str.strip().str.title()
imdb=imdb.drop(columns=['titleType','originalTitle','isAdult','endYear'])

In [93]:
imdb.columns

Index(['tconst', 'primaryTitle', 'startYear', 'runtimeMinutes', 'genres'], dtype='object')

In [94]:
#This is Oscar Nominated movies list 
top=pd.read_csv('data/all_best_pic_nominated.csv',  encoding='latin-1')
top['Title']=top['Title'].str.strip().str.title()
top=top.drop(columns=['Position','IMDb Rating', 'Num Votes','Created','Modified','Description','URL','Title Type','Release Date', 'Directors'])
top=top[['Const', 'Title', 'Year', 'Runtime (mins)', 'Genres']]
top.columns=['tconst', 'primaryTitle', 'startYear', 'runtimeMinutes', 'genres']

In [95]:
#Function to first map Oscar Nominations list, then imdb overall 

def merge_imdb(picture):
    merge=picture.merge(top, left_on=['Nominee', 'Year_film'], right_on=['primaryTitle','startYear'], how='inner')
    missing=[]
    pictures=picture['Nominee'].to_list()
    for pic in pictures:
        if pic not in np.array(merge['Nominee']):
            missing.append(pic)
        
    to_match=picture[picture['Nominee'].isin(missing)]
    merge2=to_match.merge(imdb, left_on=['Nominee', 'Year_film'], right_on=['primaryTitle','startYear'], how='inner')
    merge3=to_match.merge(imdb, left_on=['Nominee', 'Year_film2'], right_on=['primaryTitle','startYear'], how='inner')
    merge4=to_match.merge(imdb, left_on=['Nominee', 'Year_film3'], right_on=['primaryTitle','startYear'], how='inner')
#    print(merge.columns, merge2.columns, merge3.columns, merge4.columns)
    final=pd.concat([merge,merge2,merge3,merge4], axis=0, sort=False)
    print(final.shape)
    return final

In [96]:
picture=merge_imdb(picture)

(438, 19)

<h2>Match IMDB ratings</h2>
Now, we're gonna match movie rating and movie  votes

In [97]:
rating=pd.read_csv('data/imdb/film_rating_num_votes.tsv', sep='\t', na_values='\\N')
picture=picture.merge(rating, on='tconst', how='left')

In [98]:
picture

,Year,Award,Movie,Nominee,Winner,ACTOR_IN_A_LEADING_ROLE_nomination,ACTOR_IN_A_SUPPORTING_ROLE_nomination,ACTRESS_IN_A_LEADING_ROLE_nomination,ACTRESS_IN_A_SUPPORTING_ROLE_nomination,DIRECTING_nomination,...,Year_film,Year_film2,Year_film3,tconst,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes
0,1942,BEST PICTURE,Metro-Goldwyn-Mayer,Blossoms In The Dust,NaN,0,0,1,0,0,...,1941,1940,1939,tt0033407,Blossoms In The Dust,1941.0,99,"Biography, Drama, Romance",6.9,1594
1,1942,BEST PICTURE,Mercury,Citizen Kane,NaN,1,0,0,0,1,...,1941,1940,1939,tt0033467,Citizen Kane,1941.0,119,"Drama, Mystery",8.3,372145
2,1942,BEST PICTURE,Columbia,Here Comes Mr. Jordan,NaN,1,1,0,0,1,...,1941,1940,1939,tt0033712,Here Comes Mr. Jordan,1941.0,94,"Comedy, Fantasy, Romance",7.6,5473
3,1942,BEST PICTURE,Paramount,Hold Back The Dawn,NaN,0,0,1,0,0,...,1941,1940,1939,tt0033722,Hold Back The Dawn,1941.0,116,"Drama, Romance",7.4,1684
4,1942,BEST PICTURE,20Th Century-Fox,How Green Was My Valley,1.0,0,1,0,1,1,...,1941,1940,1939,tt0033729,How Green Was My Valley,1941.0,118,"Drama, Family",7.7,19621
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433,1987,BEST PICTURE,"Ismail Merchant, Producer",A Room With A View,NaN,0,1,0,1,1,...,1986,1985,1984,tt0091867,A Room With A View,1985.0,117,"Drama,Romance",7.3,36755
434,1996,BEST PICTURE,"Mario Cecchi Gori, Vittorio Cecchi Gori And Ga...",Il Postino,NaN,1,0,0,0,1,...,1995,1994,1993,tt0110877,Il Postino,1994.0,108,"Biography,Comedy,Drama",7.7,31212
435,1999,BEST PICTURE,"Elda Ferri And Gianluigi Braschi, Producers",Life Is Beautiful,NaN,1,0,0,0,1,...,1998,1997,1996,tt0118799,Life Is Beautiful,1997.0,116,"Comedy,Drama,Romance",8.6,571116
436,2006,BEST PICTURE,"Paul Haggis And Cathy Schulman, Producers",Crash,1.0,0,1,0,0,1,...,2005,2004,2003,tt0375679,Crash,2004.0,112,"Crime,Drama,Thriller",7.8,405021
437,2010,BEST PICTURE,"Kathryn Bigelow, Mark Boal, Nicolas Chartier A...",The Hurt Locker,1.0,1,0,0,0,1,...,2009,2008,2007,tt0887912,The Hurt Locker,2008.0,131,"Drama,Thriller,War",7.6,399576

<h2>Add director's age</h2>

In [99]:
director = pd.read_csv('data/imdb/title_to_director_writer.tsv', sep='\t', na_values='\\N')
picture=picture.merge(director, on='tconst', how='left')

#Add age 
dire = pd.read_csv('data/imdb/directors_actors_data.tsv', sep='\t', na_values='\\N')
picture['director']=picture['directors'].str.split(',').str[0]
picture=picture.merge(dire[['nconst','birthYear']], left_on='director', right_on='nconst', how='left')

In [100]:
picture['dir_age']=picture['Year']-picture['birthYear']

In [101]:
#Add gender 

gender = pd.read_csv('data/Gender - gender.csv')

In [102]:
picture=picture.merge(gender[['nconst','is_woman']], left_on='director', right_on='nconst')

<h2>Add scraped stuff </h2>

In [103]:
picture[['tconst']].to_csv('data/movies to crawl.csv')

In [104]:
stuff=pd.read_csv('data/scraped_movie_info.csv')

In [105]:
new=picture.merge(stuff, left_on='tconst', right_on='tconst', how='left')

In [106]:
new['winner_bool']=new['Winner']==1

In [107]:
new.columns

Index(['Year', 'Award', 'Movie', 'Nominee', 'Winner',
       'ACTOR_IN_A_LEADING_ROLE_nomination',
       'ACTOR_IN_A_SUPPORTING_ROLE_nomination',
       'ACTRESS_IN_A_LEADING_ROLE_nomination',
       'ACTRESS_IN_A_SUPPORTING_ROLE_nomination', 'DIRECTING_nomination',
       'CINEMATOGRAPHY_nomination', 'Year_film', 'Year_film2', 'Year_film3',
       'tconst', 'primaryTitle', 'startYear', 'runtimeMinutes', 'genres',
       'averageRating', 'numVotes', 'directors', 'writers', 'director',
       'nconst_x', 'birthYear', 'dir_age', 'nconst_y', 'is_woman', 'name',
       'release_day', 'rating', 'metascore', 'budget', 'opening_wk',
       'opening_usa_day', 'gross', 'world', 'release_month',
       'release_day_of_month', 'winner_bool'],
      dtype='object')

<h2>Do the same with the test data</h2>

In [108]:
osc2020['Year']=2020
osc2020.columns=['Award','Nominee','Movie','Year']

osc2020['Award']=osc2020['Award'].map(dict)
pic2020 = osc2020[osc2020['Award']=='BEST PICTURE']


pic2020=match_awards(osc2020, pic2020)
pic2020

,Award,Nominee,Movie,Year,ACTOR_IN_A_LEADING_ROLE_nomination,ACTRESS_IN_A_LEADING_ROLE_nomination,ACTOR_IN_A_SUPPORTING_ROLE_nomination,ACTRESS_IN_A_SUPPORTING_ROLE_nomination,DIRECTING_nomination,CINEMATOGRAPHY_nomination
0,BEST PICTURE,Ford V Ferrari,Ford V Ferrari,2020,False,False,False,False,False,False
1,BEST PICTURE,The Irishman,The Irishman,2020,False,False,True,False,True,True
2,BEST PICTURE,Jojo Rabbit,Jojo Rabbit,2020,False,False,False,True,False,False
3,BEST PICTURE,Joker,Joker,2020,True,False,False,False,True,True
4,BEST PICTURE,Little Women,Little Women,2020,False,True,False,True,False,False
5,BEST PICTURE,Marriage Story,Marriage Story,2020,True,True,False,True,False,False
6,BEST PICTURE,1917,1917,2020,False,False,False,False,True,True
7,BEST PICTURE,Once Upon A Time... In Hollywood,Once Upon A Time... In Hollywood,2020,True,False,True,False,True,True
8,BEST PICTURE,Parasite,Parasite,2020,False,False,False,False,True,False

In [109]:

pic2020['Year_film']=pic2020['Year']-1
pic2020 ['Year_film2']=pic2020['Year']-2
pic2020 ['Year_film3']=pic2020['Year']-3

pic2020=merge_imdb(pic2020)
pic2020

(10, 18)

,Award,Nominee,Movie,Year,ACTOR_IN_A_LEADING_ROLE_nomination,ACTRESS_IN_A_LEADING_ROLE_nomination,ACTOR_IN_A_SUPPORTING_ROLE_nomination,ACTRESS_IN_A_SUPPORTING_ROLE_nomination,DIRECTING_nomination,CINEMATOGRAPHY_nomination,Year_film,Year_film2,Year_film3,tconst,primaryTitle,startYear,runtimeMinutes,genres
0,BEST PICTURE,Ford V Ferrari,Ford V Ferrari,2020,False,False,False,False,False,False,2019,2018,2017,tt1950186,Ford V Ferrari,2019.0,152,"Action,Biography,Drama"
1,BEST PICTURE,The Irishman,The Irishman,2020,False,False,True,False,True,True,2019,2018,2017,tt1302006,The Irishman,2019.0,209,"Biography,Crime,Drama"
2,BEST PICTURE,Jojo Rabbit,Jojo Rabbit,2020,False,False,False,True,False,False,2019,2018,2017,tt2584384,Jojo Rabbit,2019.0,108,"Comedy,Drama,War"
3,BEST PICTURE,Joker,Joker,2020,True,False,False,False,True,True,2019,2018,2017,tt7286456,Joker,2019.0,122,"Crime,Drama,Thriller"
4,BEST PICTURE,Little Women,Little Women,2020,False,True,False,True,False,False,2019,2018,2017,tt3281548,Little Women,2019.0,135,"Drama,Romance"
5,BEST PICTURE,Marriage Story,Marriage Story,2020,True,True,False,True,False,False,2019,2018,2017,tt7653254,Marriage Story,2019.0,137,"Comedy,Drama,Romance"
6,BEST PICTURE,1917,1917,2020,False,False,False,False,True,True,2019,2018,2017,tt8579674,1917,2019.0,119,"Drama,War"
7,BEST PICTURE,Once Upon A Time... In Hollywood,Once Upon A Time... In Hollywood,2020,True,False,True,False,True,True,2019,2018,2017,tt7131622,Once Upon A Time... In Hollywood,2019.0,161,"Comedy,Drama"
8,BEST PICTURE,Parasite,Parasite,2020,False,False,False,False,True,False,2019,2018,2017,tt6751668,Parasite,2019.0,132,"Comedy,Crime,Drama"
0,BEST PICTURE,Little Women,Little Women,2020,False,True,False,True,False,False,2019,2018,2017,tt6495094,Little Women,2018.0,112,"Drama,Family"

In [110]:
#add ratings 
pic2020=pic2020.merge(rating, on='tconst', how='left')

In [111]:
pic2020=pic2020[:9]

In [112]:
pic2020.iloc[4,18]=8.1
pic2020.iloc[4,19]=43284
pic2020.iloc[6,18]=8.5
pic2020.iloc[6,19]=133686

pic2020

,Award,Nominee,Movie,Year,ACTOR_IN_A_LEADING_ROLE_nomination,ACTRESS_IN_A_LEADING_ROLE_nomination,ACTOR_IN_A_SUPPORTING_ROLE_nomination,ACTRESS_IN_A_SUPPORTING_ROLE_nomination,DIRECTING_nomination,CINEMATOGRAPHY_nomination,Year_film,Year_film2,Year_film3,tconst,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes
0,BEST PICTURE,Ford V Ferrari,Ford V Ferrari,2020,False,False,False,False,False,False,2019,2018,2017,tt1950186,Ford V Ferrari,2019.0,152,"Action,Biography,Drama",8.3,25656.0
1,BEST PICTURE,The Irishman,The Irishman,2020,False,False,True,False,True,True,2019,2018,2017,tt1302006,The Irishman,2019.0,209,"Biography,Crime,Drama",8.7,11039.0
2,BEST PICTURE,Jojo Rabbit,Jojo Rabbit,2020,False,False,False,True,False,False,2019,2018,2017,tt2584384,Jojo Rabbit,2019.0,108,"Comedy,Drama,War",8.1,11237.0
3,BEST PICTURE,Joker,Joker,2020,True,False,False,False,True,True,2019,2018,2017,tt7286456,Joker,2019.0,122,"Crime,Drama,Thriller",8.8,477203.0
4,BEST PICTURE,Little Women,Little Women,2020,False,True,False,True,False,False,2019,2018,2017,tt3281548,Little Women,2019.0,135,"Drama,Romance",8.1,43284.0
5,BEST PICTURE,Marriage Story,Marriage Story,2020,True,True,False,True,False,False,2019,2018,2017,tt7653254,Marriage Story,2019.0,137,"Comedy,Drama,Romance",8.3,2228.0
6,BEST PICTURE,1917,1917,2020,False,False,False,False,True,True,2019,2018,2017,tt8579674,1917,2019.0,119,"Drama,War",8.5,133686.0
7,BEST PICTURE,Once Upon A Time... In Hollywood,Once Upon A Time... In Hollywood,2020,True,False,True,False,True,True,2019,2018,2017,tt7131622,Once Upon A Time... In Hollywood,2019.0,161,"Comedy,Drama",8.0,230779.0
8,BEST PICTURE,Parasite,Parasite,2020,False,False,False,False,True,False,2019,2018,2017,tt6751668,Parasite,2019.0,132,"Comedy,Crime,Drama",8.6,77415.0

In [113]:
#add director's age and gender 

pic2020=pic2020.merge(director, on='tconst', how='left')

pic2020['director']=pic2020['directors'].str.split(',').str[0]

In [114]:
#Age 
pic2020=pic2020.merge(dire[['nconst','birthYear']], left_on='director', right_on='nconst', how='left')
pic2020['dir_age']=pic2020['Year']-pic2020['birthYear']
pic2020['is_woman']=0

In [115]:
#Add scraped data
data=pd.read_csv('data/scraped_movie_info2020.csv')

pic2020=pic2020.merge(data, on='tconst')

In [116]:
# pic2020.to_csv('test.csv', index=False)
# new.to_csv('train.csv', index=False)

In [117]:
pic2020

,Award,Nominee,Movie,Year,ACTOR_IN_A_LEADING_ROLE_nomination,ACTRESS_IN_A_LEADING_ROLE_nomination,ACTOR_IN_A_SUPPORTING_ROLE_nomination,ACTRESS_IN_A_SUPPORTING_ROLE_nomination,DIRECTING_nomination,CINEMATOGRAPHY_nomination,...,release_day,rating,metascore,budget,opening_wk,opening_usa_day,gross,world,release_month,release_day_of_month
0,BEST PICTURE,Ford V Ferrari,Ford V Ferrari,2020,False,False,False,False,False,False,...,2019-11-15,PG-13,81.0,97600000.0,31474958.0,17 November 2019,114695854.0,2.201200e+08,11,15
1,BEST PICTURE,The Irishman,The Irishman,2020,False,False,True,False,True,True,...,2019-11-27,R,94.0,159000000.0,NaN,NaN,961224.0,NaN,11,27
2,BEST PICTURE,Jojo Rabbit,Jojo Rabbit,2020,False,False,False,True,False,False,...,2019-11-08,PG-13,NaN,NaN,349555.0,20 October 2019,27980411.0,6.488116e+07,11,8
3,BEST PICTURE,Joker,Joker,2020,True,False,False,False,True,True,...,2019-10-04,R,NaN,55000000.0,96202337.0,6 October 2019,334873263.0,1.071173e+09,10,4
4,BEST PICTURE,Little Women,Little Women,2020,False,True,False,True,False,False,...,2019-12-25,PG,91.0,40000000.0,16755310.0,29 December 2019,95755632.0,1.493520e+08,12,25
5,BEST PICTURE,Marriage Story,Marriage Story,2020,True,True,False,True,False,False,...,2019-12-06,R,93.0,18600000.0,NaN,NaN,NaN,3.233820e+05,12,6
6,BEST PICTURE,1917,1917,2020,False,False,False,False,True,True,...,2020-01-10,R,78.0,100000000.0,576216.0,29 December 2019,109586389.0,2.079864e+08,1,10
7,BEST PICTURE,Once Upon A Time... In Hollywood,Once Upon A Time... In Hollywood,2020,True,False,True,False,True,True,...,2019-07-26,R,83.0,90000000.0,41082018.0,28 July 2019,141895661.0,3.891451e+08,7,26
8,BEST PICTURE,Parasite,Parasite,2020,False,False,False,False,True,False,...,2019-11-08,R,96.0,NaN,41082018.0,28 July 2019,141895661.0,3.891451e+08,11,8

In [118]:
#### More wrangling of the data -- to the final set

In [119]:
# traindata=pd.read_csv('train.csv')  new
# test=pd.read_csv('test.csv') pic2020

In [120]:
#Import CPI data
cpi = pd.read_csv('data/CPIAUCNS.csv')
cpi['year']=pd.to_datetime(cpi['DATE']).dt.year
cpi=cpi.groupby('year').first().reset_index()


# create index multiplier
#inflation[‘CPI_Multiplier’] = inflation[‘CPI’].iloc[-1] / inflation[‘CPI’]

cpi['cpi_multiplier']=cpi['CPIAUCNS'].iloc[-1]/cpi['CPIAUCNS']
cpi=cpi.drop(columns=['CPIAUCNS','DATE'])
cpi.loc[cpi.shape[0]]=[2020, 1]

In [121]:
#Define function to get_dummies for genres
import numpy as np
concat=pd.concat([new['genres'].str.split(',').str[0], new['genres'].str.split(',').str[1], new['genres'].str.split(',').str[2]], axis=0).unique()
genres=pd.Series(concat).str.strip().str.lower().unique()



def add_genres(X):
    X['genres']=X['genres'].str.lower()
    for genre in genres:
        if pd.isnull(genre)==False:
            X[genre]=X['genres'].str.contains(genre)
    return X




#Define function to get N globes 

def n_globes(X):
    globes = pd.read_csv('data/golden_globe_awards.csv')
    get_films=X.merge(globes[['film','win','category']], left_on='nominee', right_on='film', how='inner')
    n_nominations=pd.DataFrame(get_films['tconst'].value_counts()).reset_index()
    n_nominations.columns=['tconst','n_globes']
    X=X.merge(n_nominations, on='tconst',how='left')
    
    
    return X

In [122]:
new['budget']=pd.to_numeric(new['budget'].str.replace("$",'').str.replace(',','')
              .str.replace('EUR','').str.replace('GBP',''))

new['budget'].dtypes=='object'

False

In [123]:
#Wrangle data 

def wrangle(X):
    
    #Columns to lower
    X.columns=X.columns.str.lower()
    
    #Get genres
    X=add_genres(X)
    
    #Make sure all budgets are numeric
    for cols in ['budget','opening_wk','gross','world']:
        if (X[cols].dtypes=='object'):
            X[cols]=pd.to_numeric(X[cols].str.replace('$','').str.replace('EUR','').str.replace('GBP','').str.replace(',',''))
    
    #Adjust box office numbers for inflation
    X=X.merge(cpi, on='year',how='left')
    X['budget']=X['budget']*X['cpi_multiplier']
    X['opening_wk']=X['opening_wk']*X['cpi_multiplier']
    X['gross']=X['gross']*X['cpi_multiplier']
    X['world']=X['world']*X['cpi_multiplier']
    
    #Get golden globes n
    X=n_globes(X)
    
    #Convert columns to correct formats

    return X

In [128]:
final_train=wrangle(new)

NameError: name 'wrange' is not defined

In [129]:
final_train.columns

Index(['year', 'award', 'movie', 'nominee', 'winner',
       'actor_in_a_leading_role_nomination',
       'actor_in_a_supporting_role_nomination',
       'actress_in_a_leading_role_nomination',
       'actress_in_a_supporting_role_nomination', 'directing_nomination',
       'cinematography_nomination', 'year_film', 'year_film2', 'year_film3',
       'tconst', 'primarytitle', 'startyear', 'runtimeminutes', 'genres',
       'averagerating', 'numvotes', 'directors', 'writers', 'director',
       'nconst_x', 'birthyear', 'dir_age', 'nconst_y', 'is_woman', 'name',
       'release_day', 'rating', 'metascore', 'budget', 'opening_wk',
       'opening_usa_day', 'gross', 'world', 'release_month',
       'release_day_of_month', 'winner_bool', 'biography', 'drama', 'comedy',
       'adventure', 'film-noir', 'mystery', 'action', 'crime', 'horror',
       'family', 'animation', 'western', 'romance', 'fantasy', 'thriller',
       'war', 'history', 'music', 'sport', 'musical', 'sci-fi',
       'cpi_multiplier', 'n_globes'],
      dtype='object')

In [130]:
final_test=wrangle(pic2020)

In [131]:
final_train.to_csv('traindata.csv', index=False)
final_test.to_csv('test.csv', index=False)